<div id="app"></div>
<div id="alert">
    <span class="close"></span>
    <div class="content"></div>
</div>
<?php if ($this->show_overlay == true) { ?>
	<div id="overlay">	
		<div class="cont">
			<span class="close"></span>
			<h2>Here's a quick tour:</h2>
			<div id="search_result_5207ec91b9c9010009a197c4" class="result">
			<div class="pic floatleft">
				<a target="_new" href="http://www.twitter.com/J_Ziggy"><img alt="" src="https://si0.twimg.com/profile_images/344513261568397923/588d84b1cf533b76c2d908971ff38293_normal.jpeg"></a>
			</div>
			<div class="value floatleft">
				<div class="info">
					<span class="name">Daj</span>&nbsp;<span class="at_tag"><a target="_new" href="http://www.twitter.com/J_Ziggy">@J_Ziggy</a></span>
				</div>	    					
				<ul class="tokens">			
					<li title="Moderately positive (+3.00)" class="moderately_positive token">great</li>			
					<li title="Somewhat positive (+2.00)" class="somewhat_positive token">opportunity</li>			
					<li title="Neutral (0.00)" class="neutral token">here</li>			
					<li title="Neutral (0.00)" class="neutral token">to</li>			
					<li title="Neutral (0.00)" class="neutral token">just</li>			
					<li title="Neutral (0.00)" class="neutral token">put</li>			
					<li title="Neutral (0.00)" class="neutral token">a</li>			
					<li title="Neutral (0.00)" class="neutral token">bullet</li>			
					<li title="Neutral (0.00)" class="neutral token">in</li>			
					<li title="Neutral (0.00)" class="neutral token">watson's</li>			
					<li title="Neutral (0.00)" class="neutral token">career.</li>			
					<li title="Neutral (0.00)" class="neutral token">we've</li>			
					<li title="Somewhat negative (-2.00)" class="somewhat_negative token">wasted</li>			
					<li title="Neutral (0.00)" class="neutral token">too</li>			
					<li title="Neutral (0.00)" class="neutral token">many</li>			
					<li title="Neutral (0.00)" class="neutral token">years</li>			
					<li title="Neutral (0.00)" class="neutral token">on</li>			
					<li title="Neutral (0.00)" class="neutral token">this</li>			
					<li title="Neutral (0.00)" class="neutral token">guy.</li>			
					<li title="Neutral (0.00)" class="neutral token">#ashes</li>			
					<li title="Neutral (0.00)" class="neutral token">#auscricket</li>						
				</ul>
			</div>
			<div class="score slightly_positive floatright" title="Slightly positive">
				+1.00
			</div>	    					
			<div class="date floatright">
				20:56:40 11/08/2013
			</div>
			<div class="clear">&nbsp;</div>
		</div>
		<img src="/assets/images/arrow.png" alt="" class="score arrow" />
		<p class="score">Calculated score of the tweet.</p>
		<img src="/assets/images/arrow.png" alt="" class="tweet arrow large" />
		<p class="tweet">The tweet lives here.</p>
		<img src="/assets/images/arrow_flip.png" alt="" class="hover arrow" />
		<p class="hover">Hover over an underlined word to see the classification details.</p>
		<img src="/assets/images/arrow_flip.png" alt="" class="class arrow large" />
		<p class="class">The more red a word is, the more negative it is. The more green, the more positive.</p>
	</div>
<?php } ?>