<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta content="initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" name="viewport" />
		<script type="text/javascript" src="/assets/js/libs/json2.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery-1.8.1.js"></script>
		<script type="text/javascript" src="/assets/js/libs/underscore-1.3.3.js"></script>
		<script type="text/javascript" src="/assets/js/libs/backbone-1.0.js"></script>
		<script type="text/javascript" src="/assets/js/libs/highcharts/highcharts.src.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery-viewport-min.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery.scrollTo-1.4.3.1-min.js"></script>
		<script type="text/javascript" src="/src/util.js"></script>
		<script type="text/javascript" src="/src/application.js"></script>
		<script type="text/javascript" src="/src/modules/base.js"></script>
		<script type="text/javascript" src="/src/modules/error.js"></script>
		<script type="text/javascript" src="/src/modules/job.js"></script>
		<script type="text/javascript" src="/src/modules/search_result.js"></script>
		<link rel="stylesheet" href="/assets/css/reset.css" type="text/css" />
		<link rel="stylesheet" href="/assets/css/app.css" type="text/css" />
		<link rel="icon" type="image/png" href="/assets/images/favicon.png" />
		<title>Consensus</title>
	</head>
	<body>
		<div id="wrapper">
			<?php echo $this->layout()->content; ?>			
		</div>
	</body>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-8308406-13', 'consensushq.com');
	  ga('send', 'pageview');

	</script>
</html>