<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta content="initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0" name="viewport" />
		<script type="text/javascript" src="/assets/js/libs/json2.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery-1.8.1.js"></script>
		<script type="text/javascript" src="/assets/js/libs/underscore-1.3.3.js"></script>
		<script type="text/javascript" src="/assets/js/libs/backbone-1.0.js"></script>
		<script type="text/javascript" src="/assets/js/libs/highcharts/highcharts.src.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery-viewport-min.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery.scrollTo-1.4.3.1-min.js"></script>
		<script type="text/javascript" src="/src/util.js"></script>
		<script type="text/javascript" src="/src/application.js"></script>
		<script type="text/javascript" src="/src/modules/base.js"></script>
		<script type="text/javascript" src="/src/modules/error.js"></script>
		<script type="text/javascript" src="/src/modules/job.js"></script>
		<script type="text/javascript" src="/src/modules/search_result.js"></script>
		<link rel="stylesheet" href="/assets/css/reset.css" type="text/css" />
		<link rel="stylesheet" href="/assets/css/global.css" type="text/css" />
		<link href="http://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css" />
        <title>Consensus</title>
	</head>
	<body>
		<div id="wrapper">
			<?php echo $this->layout()->content; ?>			
		</div>
	</body>
</html>