<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
	</head>
	<body>
		<div id="header">
			<?php if (Zend_Registry::isRegistered('user')) { ?>
				<a href="/authentication/logout">Log out</a>
			<?php } ?>
		</div>
		<?php if (isset($this->MessageFlash) && $this->MessageFlash->errorsCount() > 0) { ?>
			<div class="message_flash error">
				<ul>
					<?php foreach ($this->MessageFlash->getErrors() as $msg) { ?>
						<li><?php echo $msg; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php if (isset($this->MessageFlash) && $this->MessageFlash->successesCount() > 0) { ?>
			<div class="message_flash success">
				<ul>
					<?php foreach ($this->MessageFlash->getSuccesses() as $msg) { ?>
						<li><?php echo $msg; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php if (isset($this->MessageFlash) && $this->MessageFlash->infosCount() > 0) { ?>
			<div class="message_flash info">
				<ul>
					<?php foreach ($this->MessageFlash->getInfos() as $msg) { ?>
						<li><?php echo $msg; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php if (isset($this->MessageFlash) && $this->MessageFlash->warningsCount() > 0) { ?>
			<div class="message_flash warning">
				<ul>
					<?php foreach ($this->MessageFlash->getWarnings() as $msg) { ?>
						<li><?php echo $msg; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php echo $this->layout()->content; ?>
	</body>
	<script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	  ga('create', 'UA-8308406-13', 'consensushq.com');
	  ga('send', 'pageview');

	</script>
</html>