<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
	</head>
	<body>
		<div id="header">
			<?php if (Zend_Registry::isRegistered('user')) { ?>
				<a href="/authentication/logout">Log out</a>
			<?php } ?>
		</div>
		<?php if (isset($this->MessageFlash) && $this->MessageFlash->errorsCount() > 0) { ?>
			<div class="message_flash error">
				<ul>
					<?php foreach ($this->MessageFlash->getErrors() as $msg) { ?>
						<li><?php echo $msg; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php if (isset($this->MessageFlash) && $this->MessageFlash->successesCount() > 0) { ?>
			<div class="message_flash success">
				<ul>
					<?php foreach ($this->MessageFlash->getSuccesses() as $msg) { ?>
						<li><?php echo $msg; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php if (isset($this->MessageFlash) && $this->MessageFlash->infosCount() > 0) { ?>
			<div class="message_flash info">
				<ul>
					<?php foreach ($this->MessageFlash->getInfos() as $msg) { ?>
						<li><?php echo $msg; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php if (isset($this->MessageFlash) && $this->MessageFlash->warningsCount() > 0) { ?>
			<div class="message_flash warning">
				<ul>
					<?php foreach ($this->MessageFlash->getWarnings() as $msg) { ?>
						<li><?php echo $msg; ?></li>
					<?php } ?>
				</ul>
			</div>
		<?php } ?>
		<?php echo $this->layout()->content; ?>
	</body>
</html>