<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<script type="text/javascript" src="/assets/js/libs/jquery-1.8.1.js"></script>
		<link rel="stylesheet" href="/assets/css/reset.css" type="text/css" />
		<link rel="stylesheet" href="/assets/css/global.css" type="text/css" />
		<link href="http://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?php echo $this->layout()->content; ?>
			<div class="clear">&nbsp;</div>
		</div>
	</body>
</html>