<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<script type="text/javascript" src="/assets/js/libs/json2.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery-1.8.1.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery-ui-1.9.0.custom.min.js"></script>
		<script type="text/javascript" src="/assets/js/libs/underscore-1.3.3.js"></script>
		<script type="text/javascript" src="/assets/js/libs/backbone-1.0.js"></script>
		<script type="text/javascript" src="/assets/js/libs/md5.js"></script>
		<script type="text/javascript" src="/assets/js/libs/highcharts/highcharts.src.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery-viewport-min.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery-color.js"></script>
		<script type="text/javascript" src="/assets/js/libs/jquery.scrollTo-1.4.3.1-min.js"></script>
		<script type="text/javascript" src="/src/util.js"></script>
		<script type="text/javascript" src="/src/application.js"></script>
		<script type="text/javascript" src="/src/modules/base.js"></script>
		<script type="text/javascript" src="/src/modules/error.js"></script>
		<script type="text/javascript" src="/src/modules/job.js"></script>
		<script type="text/javascript" src="/src/modules/search_result.js"></script>
		<link rel="stylesheet" href="/assets/css/reset.css" type="text/css" />
		<link rel="stylesheet" href="/assets/css/global.css" type="text/css" />
		<link rel="stylesheet" type="text/css" href="/assets/css/redmond/jquery-ui-1.9.0.custom.css" />
		<link href="http://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet" type="text/css" />
        <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?php echo $this->layout()->content; ?>
			<div class="clear">&nbsp;</div>
		</div>
		<div id="message"></div>
		<div id="throbber" class="bluegray-grad"><img src="/assets/images/throbber_big.gif" alt="Loading..." /></div>
	</body>
</html>