<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<script type="text/javascript" src="/assets/js/libs/jquery-1.8.1.js"></script>
		<script type="text/javascript" src="/assets/js/libs/bxslider-min.js"></script>
		<script type="text/javascript" src="/assets/js/site.js"></script>
		<link rel="stylesheet" href="/assets/css/reset.css" type="text/css" />
		<link rel="stylesheet" href="/assets/css/site.css" type="text/css" />
		<link rel="stylesheet" href="/assets/css/bxslider.css" type="text/css" />
		<link rel="icon" type="image/png" href="/assets/images/favicon.png" />
		<title>Consensus</title>
	</head>
	<body>
		<div id="container">
			<?php echo $this->layout()->content; ?>
			<div class="clear">&nbsp;</div>
		</div>
	</body>
</html>