<div id="header">
	<div class="cont">
		<div class="floatleft">
			<a href="/"><img src="/assets/images/logo.png?<?php echo md5(uniqid()); ?>" alt="Consensus"></a>
		</div>
		<div class="floatright" id="signin">
			<a href="/auth/login"><img src="/assets/images/sign_in_small.png" alt="Sign in" /></a>
		</div>
		<div class="clear">&nbsp;</div>
	</div>
</div>
<div id="content">
	<div class="cont">
		<div class="floatleft">
			<h2>Analyse the sentiment of tweets in real-time.</h2>
			<ul>
				<li>View the positive/negative numerical rating of collected tweets.</li>
				<li>Chart the average score of a search over time.</li>
				<li>Source the crowd perception of a keyword/brand/person/trend.</li>
				<li>Sign in for free using your Twitter account.</li>
			</ul>
			<a href="/auth/login"><img src="/assets/images/sign_in.png" alt="Sign in" /></a>
		</div>
		<div class="floatright alignright">
			<ul class="slider">
				<li><img src="/assets/images/screenshot.png" alt="The app" /></li>
				<li><img src="/assets/images/screenshot.png" alt="The app" /></li>
				<li><img src="/assets/images/screenshot.png" alt="The app" /></li>
			</ul>
		</div>
		<div class="clear">&nbsp;</div>
	</div>
</div>
<div id="howitworks">
	<div class="cont">
		<h2>How it works:</h2>		
		<ul>
			<li class="floatleft">
				<img src="/assets/images/screenshot.png" alt="The app" />
				<p>Bacon ipsum dolor sit amet fatback doner tail meatball venison shank. Pork belly bacon venison shank, flank jowl bresaola capicola ground round tongue shoulder pork loin strip steak sausage.</p>
			</li>
			<li class="floatright">
				<p>Bacon ipsum dolor sit amet fatback doner tail meatball venison shank. Pork belly bacon venison shank, flank jowl bresaola capicola ground round tongue shoulder pork loin strip steak sausage.</p>
				<img src="/assets/images/screenshot.png" alt="The app" />
			</li>
			<li class="floatleft">
				<img src="/assets/images/screenshot.png" alt="The app" />
				<p>Bacon ipsum dolor sit amet fatback doner tail meatball venison shank. Pork belly bacon venison shank, flank jowl bresaola capicola ground round tongue shoulder pork loin strip steak sausage.</p>
			</li>
			<li class="floatright">
				<p>Bacon ipsum dolor sit amet fatback doner tail meatball venison shank. Pork belly bacon venison shank, flank jowl bresaola capicola ground round tongue shoulder pork loin strip steak sausage.</p>
				<img src="/assets/images/screenshot.png" alt="The app" />
			</li>			
		</ul>
	</div>
	<div class="clear">&nbsp;</div>
</div>
<div id="footer">
	<div class="cont centre">
		&copy; <a href="http://www.newlinelabs.com">Newline Labs</a> <?php echo date('Y'); ?>
	</div>
</div>