<div id="header">
	<div class="cont">
		<div class="floatleft">
			<a href="/"><img src="/assets/images/logo.png?<?php echo md5(uniqid()); ?>" alt="Consensus"></a>
		</div>
		<div class="floatright" id="signin">
			<a href="/auth/login"><img src="/assets/images/sign_in_small.png" alt="Sign in" /></a>
		</div>
		<div class="clear">&nbsp;</div>
	</div>
</div>
<div id="content">
	<div class="cont">
		<div class="floatleft">
			<h2>Analyse the sentiment of tweets in real-time</h2>
			<ul>
				<li>View the positive/negative numerical rating of collected tweets</li>
				<li>Chart the average score of a search over time</li>
				<li>Analyse the crowd perception of a keyword/brand/person/trend</li>
			</ul>
			<a href="/auth/login"><img src="/assets/images/sign_in.png" alt="Sign in" /></a>
		</div>
		<div class="floatright alignright">
			<ul class="slider">
				<li><img src="/assets/images/screenshot.png" alt="The app" /></li>
				<li><img src="/assets/images/screenshot.png" alt="The app" /></li>
				<li><img src="/assets/images/screenshot.png" alt="The app" /></li>
			</ul>
		</div>
		<div class="clear">&nbsp;</div>
	</div>
</div>
<div id="footer">
	<div class="cont">
		<h2>How it works</h2>		
	</div>
</div>
<div class="cont centre copy">&copy; <a href="http://www.newlinelabs.com">Newline Labs</a> <?php echo date('Y'); ?></div>